; INDX_WRITE_STATE - persist INDX calibration + latch state across reboots
;
; Guard-only: performs NO motion. Writes /sys/indx-state.g, which INDX_variables.g runs on
; startup (and on a manual refresh) to restore the saved values.
;
; As well as the saved globals, the file contains the M558 V command that applies the
; calibrated scale to the probe, so the calibration takes effect on the hardware after a reboot
; and not just in a variable. V is applied to the existing probe created by config.g, so none
; of the other probe settings (speeds, dive heights, averaging, G31) are disturbed.
;
; Re-run this whenever a persisted value changes: after INDX_LC_CAL, or after the sign check
; inverts the scale.
;
; Persisted: INDX_LC_scale (= M558 V, g/count), INDX_LC_calibrated, INDX_State, INDX_LC_DEBUG.
; (INDX_LC_locking_force, INDX_LC_samples and INDX_LC_trigger_grams are config constants.)
; INDX_LC_offset is deliberately NOT restored - see the note next to it below.
;
; Run this after changing anything persisted, not just after a calibration. To keep the debug
; flag on across a reboot: set global.INDX_LC_DEBUG = 1, then M98 P"INDX_WRITE_STATE.g".

if !exists(global.INDX_LC_offset) || !exists(global.INDX_LC_scale) || !exists(global.INDX_LC_calibrated) || !exists(global.INDX_State)
  abort "INDX_WRITE_STATE: INDX globals missing. INDX_variables.g must run from config.g first."

var dbg = exists(global.INDX_LC_DEBUG) ? global.INDX_LC_DEBUG : 0
var f = "0:/sys/indx-state.g"

echo >{var.f} "; INDX persisted state - generated by INDX_WRITE_STATE, do not edit by hand."
echo >>{var.f} "; Run by INDX_variables.g to restore saved values and apply them to the probe."
; The unloaded baseline is written as a comment, not restored. It is only used during a
; calibration, where INDX_LC_CAL subtracts it from the loaded reading, and the raw zero of the
; cell drifts with temperature. Restoring a baseline captured days earlier would let a
; calibration run without a fresh INDX_TARE and produce a quietly wrong scale - a few hundred
; counts of drift against a delta of a few thousand is a few percent of error, which is too
; small for the range check to catch. Kept here only as a record of what the cell read.
echo >>{var.f} {"; unloaded baseline when calibrated: " ^ global.INDX_LC_offset ^ " counts"}
echo >>{var.f} {"set global.INDX_LC_scale = " ^ global.INDX_LC_scale}
echo >>{var.f} {"set global.INDX_LC_calibrated = " ^ global.INDX_LC_calibrated}
echo >>{var.f} {"set global.INDX_State = " ^ global.INDX_State}
; Persist the debug flag too. INDX_variables.g sets it to 0 every time it runs, so without this
; it is lost on a reboot and on every manual refresh of the variables file, which is exactly
; when a debugging session is least likely to want it turned off. Set it, then run this macro
; to make it stick.
echo >>{var.f} {"set global.INDX_LC_DEBUG = " ^ var.dbg}
echo >>{var.f} {"M558 K0 V" ^ global.INDX_LC_scale}

if var.dbg > 0
  echo {"INDX_WRITE_STATE: saved to " ^ var.f ^ "  (scale " ^ global.INDX_LC_scale ^ " g/count, state " ^ global.INDX_State ^ ")"}
